# Generated by Django 3.1.2 on 2021-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='User Email')),
                ('uuid', models.UUIDField(editable=False, verbose_name='User UUID')),
                ('type', models.CharField(choices=[('Publisher', 'Publisher'), ('Subscriber', 'Subscriber')], default='Subscriber', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
