# Generated by Django 3.1.2 on 2021-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default='11f4405f-7d3f-44af-bda4-922fab82dc83', primary_key=True, serialize=False),
        ),
    ]
