# Generated by Django 3.1.2 on 2021-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210509_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default='7e6c0bba-31fd-4b86-9649-5f0d18c2d7a6', primary_key=True, serialize=False),
        ),
    ]
