# Generated by Django 3.1.2 on 2021-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210509_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(auto_created=True, default='030da8d7-b628-4007-943f-c8e46a157d6d', primary_key=True, serialize=False),
        ),
    ]
