# Generated by Django 3.1.2 on 2021-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210509_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='1c018778-a050-48c9-9726-52b63371ac79', primary_key=True, serialize=False),
        ),
    ]
