# Generated by Django 3.1.2 on 2021-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210509_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='c188052e-b547-4e24-abc2-bed107c9c412', primary_key=True, serialize=False),
        ),
    ]
