# Generated by Django 3.1.2 on 2021-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210509_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='8fc935e2-013a-4ce5-be1e-c93750258fa9', primary_key=True, serialize=False),
        ),
    ]
