# Generated by Django 3.1.2 on 2021-05-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210509_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='dc7c18c5-d603-44fa-810f-4a56a070fd79', primary_key=True, serialize=False),
        ),
    ]
