# Generated by Django 3.1.2 on 2021-05-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210516_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='cdda84e6-0232-4cf3-bb06-4586699d510f', primary_key=True, serialize=False),
        ),
    ]
