# Generated by Django 3.1.2 on 2021-05-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210516_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='f0881181-885e-4ed7-ba66-7947004dde23', primary_key=True, serialize=False),
        ),
    ]
