# Generated by Django 3.1.2 on 2021-05-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210516_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='808959c0-3d50-4c23-95b9-fed98156970c', primary_key=True, serialize=False),
        ),
    ]
