# Generated by Django 3.1.2 on 2021-05-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishCompany',
            fields=[
                ('pub_uuid', models.UUIDField(default='2c2684ad-86c3-4f7e-9f9e-eb14d88a1f87', primary_key=True, serialize=False, verbose_name='id')),
                ('pub_company', models.CharField(max_length=15, verbose_name='Publishing Company Name')),
                ('pub_descript', models.CharField(max_length=30, verbose_name='Description')),
            ],
        ),
    ]
