# Generated by Django 3.1.2 on 2021-05-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_publishcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_uuid', models.UUIDField(default='c2225402-6e1c-4387-a87b-14f1afba41e9', verbose_name='PublishCompany')),
                ('book_name', models.CharField(max_length=50, verbose_name='Book Name')),
            ],
        ),
        migrations.AlterField(
            model_name='publishcompany',
            name='pub_uuid',
            field=models.UUIDField(default='a0f6ac53-ba54-45f9-9710-063cd99a4682', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
