# Generated by Django 3.1.2 on 2021-05-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210516_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_uuid',
            field=models.UUIDField(default='fa68313b-f072-4c70-b3fd-10dc052a7e93', verbose_name='PublishCompany'),
        ),
        migrations.AlterField(
            model_name='publishcompany',
            name='pub_uuid',
            field=models.UUIDField(default='11b6aee4-cea4-4838-8a2a-5895d423e845', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
