# Generated by Django 3.1.2 on 2021-05-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210516_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_uuid',
            field=models.UUIDField(default='a7318086-7961-4039-931b-e17c5d5b394b', verbose_name='PublishCompany'),
        ),
        migrations.AlterField(
            model_name='publishcompany',
            name='pub_uuid',
            field=models.UUIDField(default='1477ebd4-7236-461b-b62e-de89b501ee35', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
